### ISSUE TITLE
Unable to compile funty on MacOS

### ISSUE THREAD

**Issue by vultix** [bjorn3/rustc_codegen_cranelift#1114]
`funty` is a crate required by `sqlx`.  To reproduce the build error, add this as a dependency:
```toml
funty = "1.0.1"
```

This is the error message I'm seeing:
```
thread 'rustc' panicked at 'ABI argument v5 should be in a register', /Users/aidan/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/1964036/cranelift/codegen/src/regalloc/coloring.rs:409:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (593fe977a 2020-11-20) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C link-arg=-undefined -C link-arg=dynamic_lookup --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
Instance { def: Item(WithOptConstParam { did: DefId(2:18122 ~ core[343e]::num::{impl#6}::rotate_left), const_param_did: None }), substs: [] } _ZN4core3num20_$LT$impl$u20$u8$GT$11rotate_left17h4a9f2e335f0d4da1E
error: could not compile `funty`
```

**Comment by bjorn3** [comment]
The `rotate_left` and `rotate_right` methods indirectly use intrinsics that lower to the `rotl` and `rotr` clif instructions. These are not yet supported for bit widths less than 32 bit. (https://github.com/bytecodealliance/wasmtime/issues/1045) If funty were to mark all methods as `#[inline]`, which they likely should, this wouldn't be a problem unless they were actually used.

**Comment by bjorn3** [comment]
With the new Cranelift backend it gives:

```
thread 'rustc' panicked at 'Multi-register value not expected', /home/bjorn/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/c07ec4c/cranelift/codegen/src/isa/x64/lower.rs:128:10
```

This happens when compiling `<i128>::rotate_left`.
