### ISSUE TITLE
Legion miscompilation

### ISSUE THREAD

**Issue by Uriopass** [bjorn3/rustc_codegen_cranelift#1143]
Back again with another miscompilation, however turning off optimizations wasn't enough.

I made a repro here (same repo but legion_bug branch):
https://github.com/Uriopass/cranelift_bug/tree/legion_bug 

Expected:
Running with `cargo run` works

Actual:
running with cg_clif gives this:
```bash
╰─» RUST_BACKTRACE=1 ~/repos/rustc_codegen_cranelift/build/cargo.sh r
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/cranelift_bug`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/legion-0.3.1/src/internals/insert.rs:110:9
stack backtrace:
   0: rust_begin_unwind
             at /home/xxx/repos/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /home/xxx/repos/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/panicking.rs:92:14
   2: <legion::internals::insert::ArchetypeWriter as core::ops::drop::Drop>::drop
             at /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/legion-0.3.1/src/internals/insert.rs:110:9
   3: core::ptr::drop_in_place<legion::internals::insert::ArchetypeWriter>
   4: legion::internals::world::World::extend
             at /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/legion-0.3.1/src/internals/world.rs:249:56
   5: legion::internals::world::World::push
             at /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/legion-0.3.1/src/internals/world.rs:205:21
   6: cranelift_bug::main
             at ./src/main.rs:5:12
   7: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
/home/xxx/repos/rustc_codegen_cranelift/build/cargo.sh: line 18: 376986 Aborted                 (core dumped) cargo "+${TOOLCHAIN}" "$cmd" "$@"
```

**Comment by bjorn3** [comment]
This is a miscompilation in the shift handling for 128bit ints. `1u128 << 0` somehow results in 0x10000000000000001. This is probably a regression caused by https://github.com/bjorn3/rustc_codegen_cranelift/commit/9c980276d81b727bb8efcbe63f51866ba19793a0. I likely won't have time today to fix it.

**Comment by bjorn3** [comment]
This only happens for `1u128 << 0`. It doesn't happen for any other shift amount.

**Comment by bjorn3** [comment]
Filled https://github.com/bytecodealliance/wasmtime/issues/2679 as upstream bug.

**Comment by Uriopass** [comment]
Upstream fixed

**Comment by bjorn3** [comment]
I haven't had time to update the Cranelift dependency yet.
