### ISSUE TITLE
Bootstrap and test suite testing crashes with SIGSEGV

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/rustc_codegen_cranelift#1179]
This happens since the last rustc sync. The cg_clif test suite passes just fine.

https://github.com/bjorn3/rustc_codegen_cranelift/runs/2849449331?check_suite_focus=true

**Comment by bjorn3** [comment]
Backtrace:

```
#0  0x0000559346c2183f in regex_automata::minimize::StateSet<S>::intersection ()
#1  0x0000559346c215c0 in regex_automata::minimize::StateSet<S>::iter ()
#2  0x0000559346c203a2 in regex_automata::minimize::Minimizer<S>::initial_partitions ()
#3  0x0000559346c2649f in <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::next ()
#4  0x0000559346c22035 in regex_automata::minimize::StateSet<S>::subtract ()
#5  0x0000559346c26455 in <core::ops::range::Range<T> as core::iter::range::RangeIteratorImpl>::spec_next ()
#6  0x0000559346c45b8e in <core::ops::range::RangeFrom<usize> as core::slice::index::SliceIndex<[T]>>::index ()
#7  0x0000559346c05fe7 in ansi_term::ansi::<impl ansi_term::style::Style>::suffix ()
#8  0x0000559346c38651 in alloc::raw_vec::RawVec<T,A>::current_memory ()
#9  0x0000559347173c58 in std::thread::Builder::spawn_unchecked::{{closure}} ()
#10 0x0000559347173b62 in std::thread::Builder::spawn_unchecked::{{closure}} ()
#11 0x0000559347173672 in std::thread::Builder::spawn_unchecked ()
#12 0x000055934716bd56 in core::ptr::non_null::NonNull<[T]>::as_non_null_ptr ()
#13 0x000055934716bfe3 in core::iter::traits::iterator::Iterator::map ()
#14 0x0000559346c29dad in core::iter::adapters::enumerate::Enumerate<I>::new ()
#15 0x0000559346bb6ee2 in hashbrown::raw::RawTable<T,A>::rehash_in_place ()
#16 0x0000559346bb53a7 in hashbrown::raw::RawTable<T,A>::reserve_rehash ()
#17 0x0000559346bb8cd1 in hashbrown::raw::RawTable<T,A>::resize ()
#18 0x0000559346bb88da in hashbrown::raw::RawTable<T,A>::resize ()
#19 0x0000559346bb8be5 in hashbrown::raw::RawTable<T,A>::resize ()
#20 0x0000559346bb8c31 in hashbrown::raw::RawTable<T,A>::resize ()
#21 0x0000559346b1aee5 in core::slice::raw::from_raw_parts_mut ()
#22 0x0000559346abc3a0 in core::ptr::unique::Unique<T>::as_ptr ()
#23 0x0000559346ab7334 in <&mut serde_json::de::Deserializer<R> as serde::de::Deserializer>::deserialize_option ()
#24 0x0000559346ab794e in <&core::option::Option<T> as core::iter::traits::collect::IntoIterator>::into_iter ()
#25 0x0000559347442fb5 in miniz_oxide::deflate::core::compress_normal ()
#26 0x000055934736b3ad in alloc::boxed::Box<T,A>::leak ()
#27 0x000055934736b1b7 in alloc::boxed::Box<T,A>::into_raw_with_allocator ()
#28 0x0000559347319a1d in <alloc::collections::btree::map::BTreeMap<K,V> as core::iter::traits::collect::IntoIterator>::into_iter ()
#29 0x000055934731bb1f in core::mem::zeroed ()
#30 0x0000559346ab7939 in <core::mem::manually_drop::ManuallyDrop<T> as core::ops::deref::DerefMut>::deref_mut ()
#31 0x0000559346b2b63f in core::ptr::mut_ptr::<impl *mut T>::is_null ()
#32 0x00007f380e95d09b in __libc_start_main (main=0x559346b2b622 <_ZN4core3ptr7mut_ptr31_$LT$impl$u20$$BP$mut$u20$T$GT$7is_null17h10f11f11e66e0765E+27>, argc=58, argv=0x7ffee6990f78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffee6990f68) at ../csu/libc-start.c:308
#33 0x00005593469e00ba in core::option::Option<T>::map ()
```

**Comment by bjorn3** [comment]
The correct backtrace goes something like this:

```
main
std::rt::lang_start
std::rt::lang_start_internal
std::panic::catch_unwind
std::panicking::try
std::panicking::try::do_call
<unnamed>
std::rt::lang_start::{{closure}}
std::sys_common::backtrace::__rust_begin_short_backtrace
core::ops::function::FnOnce::call_once
compiletest::main
tracing_subscriber::fmt::init
...
```

**Comment by bjorn3** [comment]
The correct backtrace is:

```
#0  0x000055555585a83f in smallvec::SmallVec<A>::spilled ()
#1  0x000055555585a5c0 in smallvec::SmallVec<A>::triple ()
#2  0x00005555558593a2 in <smallvec::SmallVec<A> as core::ops::deref::Deref>::deref ()
#3  0x000055555585f49f in tracing_subscriber::filter::env::directive::DirectiveSet<tracing_subscriber::filter::env::directive::Directive>::has_value_filters::{{closure}} ()
#4  0x000055555585b035 in <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::any ()
#5  0x000055555585f455 in tracing_subscriber::filter::env::directive::DirectiveSet<tracing_subscriber::filter::env::directive::Directive>::has_value_filters ()
#6  0x000055555587eb8e in <tracing_subscriber::filter::env::EnvFilter as tracing_subscriber::layer::Layer<S>>::max_level_hint ()
#7  0x000055555583efe7 in <tracing_subscriber::layer::Layered<L,S> as tracing_core::subscriber::Subscriber>::max_level_hint ()
#8  0x0000555555871651 in <tracing_subscriber::fmt::Subscriber<N,E,F,W> as tracing_core::subscriber::Subscriber>::max_level_hint ()
#9  0x0000555555dacc58 in tracing_core::dispatcher::Dispatch::max_level_hint ()
#10 0x0000555555dacb62 in tracing_core::callsite::Registry::rebuild_interest::{{closure}} ()
#11 0x0000555555dac672 in alloc::vec::Vec<T,A>::retain ()
#12 0x0000555555da4d56 in tracing_core::callsite::Registry::rebuild_interest ()
#13 0x0000555555da4fe3 in tracing_core::callsite::register_dispatch ()
#14 0x0000555555862dad in tracing_core::dispatcher::Dispatch::new ()
#15 0x00005555557efee2 in <tracing_core::dispatcher::Dispatch as core::convert::From<S>>::from ()
#16 0x00005555557ee3a7 in <T as core::convert::Into<U>>::into ()
#17 0x00005555557f1cd1 in tracing_subscriber::util::SubscriberInitExt::try_init ()
#18 0x00005555557f18da in tracing_subscriber::fmt::SubscriberBuilder<N,E,F,W>::try_init ()
#19 0x00005555557f1be5 in tracing_subscriber::fmt::try_init ()
#20 0x00005555557f1c31 in tracing_subscriber::fmt::init ()
#21 0x0000555555753ee5 in compiletest::main ()
#22 0x00005555556f53a0 in core::ops::function::FnOnce::call_once ()
#23 0x00005555556f0334 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#24 0x00005555556f094e in std::rt::lang_start::{{closure}} ()
#25 0x000055555607bfb5 in core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once ()
#26 0x0000555555fa43ad in std::panicking::try::do_call ()
#27 0x0000555555fa41b7 in std::panicking::try ()
#28 0x0000555555f52a1d in std::panic::catch_unwind ()
#29 0x0000555555f54b1f in std::rt::lang_start_internal ()
#30 0x00005555556f0939 in std::rt::lang_start ()
#31 0x000055555576463f in main ()
#32 0x00007ffff7c3109b in __libc_start_main (main=0x555555764622 <main>, argc=58, argv=0x7fffffffd848, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd838) at ../csu/libc-start.c:308
#33 0x00005555556190ba in _start ()
```

**Comment by bjorn3** [comment]
The wrong vtable access offset was used.
