### ISSUE TITLE
Crash when compiling rg3d

### ISSUE THREAD

**Issue by martin-t** [bjorn3/rustc_codegen_cranelift#1200]
Using the prebuilt cg_clif-Linux from https://github.com/bjorn3/rustc_codegen_cranelift/actions/runs/1298261847

It says the `xcb` crate is the issue but i tried cloning and compiling it (both the most recent version and the 0.9 tag that rg3d uses) and it succeeded. So i gave up trying to find a smaller repro.

Rg3d is from https://github.com/rg3dengine/rg3d on commit de970cd722126559473d751e8a69abb23968665d

Command: `~/Programs/cg_clif/build/cargo build`

Error message:

```
thread 'rustc' panicked at 'StructArgument size is not properly aligned', /home/runner/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/bae4ec6/cranelift/codegen/src/isa/x64/abi.rs:163:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/bjorn3/rustc_codegen_cranelift/issues/new

note: rustc 1.57.0-nightly (c02371c44 2021-10-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn render::set_picture_transform(_1: &base::Connection, _2: u32, _3: render::Transform) -> base::Cookie<ffi::base::xcb_void_cookie_t> {
    debug c => _1;                       // in scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2177:34: 2177:35
    debug picture => _2;                 // in scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2178:34: 2178:41
    debug transform => _3;               // in scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2179:34: 2179:43
    let mut _0: base::Cookie<ffi::base::xcb_void_cookie_t>; // return place in scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2180:12: 2180:32
    let mut _5: *mut ffi::base::xcb_connection_t; // in scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2182:55: 2182:71
    let mut _6: &base::Connection;       // in scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2182:55: 2182:71
    let mut _7: u32;                     // in scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2183:55: 2183:86
    let mut _8: ffi::render::xcb_render_transform_t; // in scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2184:55: 2184:69
    let mut _9: ffi::base::xcb_void_cookie_t; // in scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2186:22: 2186:28
    let mut _10: &base::Connection;      // in scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2187:22: 2187:23
    scope 1 {
        let _4: ffi::base::xcb_void_cookie_t; // in scope 1 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2182:13: 2182:19
        scope 2 {
            debug cookie => _4;          // in scope 2 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2182:13: 2182:19
        }
    }

    bb0: {
        _6 = _1;                         // scope 1 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2182:55: 2182:71
        _5 = base::Connection::get_raw_conn(move _6) -> bb1; // scope 1 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2182:55: 2182:71
                                         // mir::Constant
                                         // + span: /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2182:57: 2182:69
                                         // + literal: Const { ty: for<'r> fn(&'r base::Connection) -> *mut ffi::base::xcb_connection_t {base::Connection::get_raw_conn}, val: Value(Scalar(<ZST>)) }
    }

    bb1: {
        _7 = _2;                         // scope 1 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2183:55: 2183:62
        _8 = (_3.0: ffi::render::xcb_render_transform_t); // scope 1 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2184:55: 2184:69
        _4 = ffi::render::xcb_render_set_picture_transform(move _5, move _7, move _8) -> bb2; // scope 1 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2182:22: 2184:70
                                         // mir::Constant
                                         // + span: /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2182:22: 2182:54
                                         // + literal: Const { ty: unsafe extern "C" fn(*mut ffi::base::xcb_connection_t, u32, ffi::render::xcb_render_transform_t) -> ffi::base::xcb_void_cookie_t {ffi::render::xcb_render_set_picture_transform}, val: Value(Scalar(<ZST>)) }
    }

    bb2: {
        _9 = _4;                         // scope 2 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2186:22: 2186:28
        _10 = _1;                        // scope 2 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2187:22: 2187:23
        (_0.0: ffi::base::xcb_void_cookie_t) = move _9; // scope 2 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2185:9: 2189:10
        (_0.1: &base::Connection) = move _10; // scope 2 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2185:9: 2189:10
        (_0.2: bool) = const false;      // scope 2 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2185:9: 2189:10
        return;                          // scope 0 at /home/martin/dev/rust/rg3d/target/debug/build/xcb-da76376a366f4803/out/render.rs:2191:2: 2191:2
    }
}

Instance { def: Item(WithOptConstParam { did: DefId(0:3191 ~ xcb[346f]::render::set_picture_transform), const_param_did: None }), substs: [] } _ZN3xcb6render21set_picture_transform17hdfc1001e20c1daffE
error: could not compile `xcb`
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by Aaron1011** [comment]
I'm running into this as well - is there an upstream issue thatI  should look at?

**Comment by Aaron1011** [comment]
Minimized:

```rust
#[repr(C)]
pub struct OtherArg {
    field1: i32,
    field2: i32,
    field3: i32,
    field4: i32,
    field5: i32,
}

extern "C" {
    pub fn the_bad_fn(val: OtherArg);
}

pub fn foo(val: OtherArg) {
    unsafe { the_bad_fn(val); }
}
```

**Comment by bjorn3** [comment]
I hadn't reported an upstream issue yet. Thanks for the minimized reproducer. Just tried to find the issue. Turns out cranelift requires the size of struct arguments to be a multiple of the pointer size. This seems to be required by the sysv abi. LLVM handles it for you, but cranelift requires you to take care of the details itself. As of f74cf39a7434c73424b9e5fddaf78996bd2b06c1 cg_clif now handles this. The minimized example now compiles. Rg3d compiles too but crashes at runtime as the fontdue crate unconditionally uses sse2 intrinsics that are unimplemented by cg_clif.
