### ISSUE TITLE
ICE: assertion failure: src/abi/mod.rs:

### ISSUE THREAD

**Issue by matthiaskrgr** [bjorn3/rustc_codegen_cranelift#1236]
code from rustc `./src/test/ui/abi/rustcall-generic.rs`
````rust
// revisions: normal opt
// check-pass
//[opt] compile-flags: -Zmir-opt-level=3

#![feature(unboxed_closures)]

extern "rust-call" fn foo<T>(_: T) {}

fn main() {
    foo(());
    foo((1, 2));
}
````

````
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`: rust-call abi requires two arguments', src/abi/mod.rs:397:9
stack backtrace:
   0:     0x7f22458a1b20 - std::backtrace_rs::backtrace::libunwind::trace::h419808c895a1be3b
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f22458a1b20 - std::backtrace_rs::backtrace::trace_unsynchronized::h4cd640051eb1546f
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f22458a1b20 - std::sys_common::backtrace::_print_fmt::h6a643b487717d871
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f22458a1b20 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h84bab1c2a632e967
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f22458fa85c - core::fmt::write::h41252a77742ac576
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/fmt/mod.rs:1198:17
   5:     0x7f22458933c5 - std::io::Write::write_fmt::h68f35cff36a534dd
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/io/mod.rs:1672:15
   6:     0x7f22458a4711 - std::sys_common::backtrace::_print::h82f0b1ac2501b6af
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f22458a4711 - std::sys_common::backtrace::print::h3dc7f0e84685b9ba
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f22458a4711 - std::panicking::default_hook::{{closure}}::h6ace3fe16ec6f7aa
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:295:22
   9:     0x7f22458a43e3 - std::panicking::default_hook::h77c1c7afb621e87c
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:314:9
  10:     0x7f224613f824 - rustc_driver[e83335c4a38137f8]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f22458a4ee6 - std::panicking::rust_panic_with_hook::h4cc32db16e14054a
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:702:17
  12:     0x7f22458a4d37 - std::panicking::begin_panic_handler::{{closure}}::h402861fe76edfc4d
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:588:13
  13:     0x7f22458a1ff4 - std::sys_common::backtrace::__rust_end_short_backtrace::he555a3759268da10
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7f22458a4a62 - rust_begin_unwind
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:584:5
  15:     0x7f22458698e3 - core::panicking::panic_fmt::hd3841d7ec8a5a967
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/panicking.rs:142:14
  16:     0x7f22458f769e - core::panicking::assert_failed_inner::hdaef202988b90cd3
  17:     0x7f223e644bf9 - core::panicking::assert_failed::hb73cfb932192d93c
  18:     0x7f223e75e975 - rustc_codegen_cranelift::abi::codegen_terminator_call::h3ee54347ad6a4b9f
  19:     0x7f223e6c514c - rustc_session::utils::<impl rustc_session::session::Session>::time::hb1b64207753ab68f
  20:     0x7f223e670a43 - rustc_codegen_cranelift::base::codegen_fn_content::h7b8d3541509a524b
  21:     0x7f223e6c471b - rustc_session::utils::<impl rustc_session::session::Session>::time::h5486530910de022b
  22:     0x7f223e66cbc1 - rustc_codegen_cranelift::base::codegen_fn::hc8e5fea087464384
  23:     0x7f223e6c316a - rustc_session::utils::<impl rustc_session::session::Session>::time::h2fc39d23b4fa3b7e
  24:     0x7f223e664114 - rustc_codegen_cranelift::driver::aot::module_codegen::h2827a110f59deab8
  25:     0x7f223e6eb1be - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h68aa13779d3bec18
  26:     0x7f223e6da8fa - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h355dce7525158f4e
  27:     0x7f223e70d47e - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h381e907e74a9d74a
  28:     0x7f223e6c2fa2 - rustc_session::utils::<impl rustc_session::session::Session>::time::h13abb3ffbb1cca82
  29:     0x7f223e6fbf64 - rustc_codegen_cranelift::driver::time::h7de8a4d08c3be2ab
  30:     0x7f223e666415 - rustc_codegen_cranelift::driver::aot::run_aot::h246f8b5585a00b3a
  31:     0x7f223e6b20d9 - <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h43a3212ba3170bbb
  32:     0x7f22482d5727 - <rustc_session[16e8265f3bee680e]::session::Session>::time::<alloc[aede580a0175a08c]::boxed::Box<dyn core[303bee78761e0753]::any::Any>, rustc_interface[edbb2596f0660065]::passes::start_codegen::{closure#0}>
  33:     0x7f22482c2d40 - <rustc_interface[edbb2596f0660065]::passes::QueryContext>::enter::<<rustc_interface[edbb2596f0660065]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[303bee78761e0753]::result::Result<alloc[aede580a0175a08c]::boxed::Box<dyn core[303bee78761e0753]::any::Any>, rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
  34:     0x7f22482cca23 - <rustc_interface[edbb2596f0660065]::queries::Queries>::ongoing_codegen
  35:     0x7f224828e8e1 - <rustc_interface[edbb2596f0660065]::interface::Compiler>::enter::<rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}::{closure#2}, core[303bee78761e0753]::result::Result<core[303bee78761e0753]::option::Option<rustc_interface[edbb2596f0660065]::queries::Linker>, rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
  36:     0x7f224828aab0 - rustc_span[550c183cd1c0caaa]::with_source_map::<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_interface[edbb2596f0660065]::interface::create_compiler_and_run<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#1}>
  37:     0x7f22482a50f2 - rustc_interface[edbb2596f0660065]::interface::create_compiler_and_run::<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>
  38:     0x7f224828a2b2 - <scoped_tls[c1a1588d7c68db11]::ScopedKey<rustc_span[550c183cd1c0caaa]::SessionGlobals>>::set::<rustc_interface[edbb2596f0660065]::interface::run_compiler<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
  39:     0x7f224828cfcf - std[a38b499b13c80ab0]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[edbb2596f0660065]::util::run_in_thread_pool_with_globals<rustc_interface[edbb2596f0660065]::interface::run_compiler<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
  40:     0x7f22482a5539 - <<std[a38b499b13c80ab0]::thread::Builder>::spawn_unchecked_<rustc_interface[edbb2596f0660065]::util::run_in_thread_pool_with_globals<rustc_interface[edbb2596f0660065]::interface::run_compiler<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>::{closure#1} as core[303bee78761e0753]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  41:     0x7f22458ae843 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6cafef397152c3f0
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/alloc/src/boxed.rs:1951:9
  42:     0x7f22458ae843 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0308246411b63a3b
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/alloc/src/boxed.rs:1951:9
  43:     0x7f22458ae843 - std::sys::unix::thread::Thread::new::thread_start::hd2e6d604897dcfa7
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys/unix/thread.rs:108:17
  44:     0x7f224568054d - <unknown>
  45:     0x7f2245705874 - clone
  46:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (f2d93935f 2022-07-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -C panic=abort -Z panic-abort-tests -Z codegen-backend=/home/matthias/vcs/github/rustc_codegen_cranelift/build/lib/librustc_codegen_cranelift.so

query stack during panic:
end of query stack
fn main() -> () {
    let mut _0: ();                      // return place in scope 0 at ./src/test/ui/abi/rustcall-generic.rs:9:11: 9:11
    let _1: ();                          // in scope 0 at ./src/test/ui/abi/rustcall-generic.rs:10:5: 10:12
    let mut _2: ();                      // in scope 0 at ./src/test/ui/abi/rustcall-generic.rs:10:9: 10:11
    let _3: ();                          // in scope 0 at ./src/test/ui/abi/rustcall-generic.rs:11:5: 11:16
    let mut _4: (i32, i32);              // in scope 0 at ./src/test/ui/abi/rustcall-generic.rs:11:9: 11:15

    bb0: {
        _1 = foo::<()>(move _2) -> bb1;  // scope 0 at ./src/test/ui/abi/rustcall-generic.rs:10:5: 10:12
                                         // mir::Constant
                                         // + span: ./src/test/ui/abi/rustcall-generic.rs:10:5: 10:8
                                         // + literal: Const { ty: extern "rust-call" fn(()) {foo::<()>}, val: Value(Scalar(<ZST>)) }
    }

    bb1: {
        Deinit(_4);                      // scope 0 at ./src/test/ui/abi/rustcall-generic.rs:11:9: 11:15
        (_4.0: i32) = const 1_i32;       // scope 0 at ./src/test/ui/abi/rustcall-generic.rs:11:9: 11:15
        (_4.1: i32) = const 2_i32;       // scope 0 at ./src/test/ui/abi/rustcall-generic.rs:11:9: 11:15
        _3 = foo::<(i32, i32)>(move _4) -> bb2; // scope 0 at ./src/test/ui/abi/rustcall-generic.rs:11:5: 11:16
                                         // mir::Constant
                                         // + span: ./src/test/ui/abi/rustcall-generic.rs:11:5: 11:8
                                         // + literal: Const { ty: extern "rust-call" fn((i32, i32)) {foo::<(i32, i32)>}, val: Value(Scalar(<ZST>)) }
    }

    bb2: {
        return;                          // scope 0 at ./src/test/ui/abi/rustcall-generic.rs:12:2: 12:2
    }
}

Instance { def: Item(WithOptConstParam { did: DefId(0:5 ~ rustcall_generic[c8fb]::main), const_param_did: None }), substs: [] } _ZN16rustcall_generic4main17h1dd55fa1c8a6c910E
````

**Comment by bjorn3** [comment]
Cg_llvm is a bit more lax than cg_clif with respect to the rust-call abi. Cg_clif only implements what is needed for closures. I did say this is not a bug.

**Comment by bjorn3** [comment]
Still fails with

```rust
#![feature(unboxed_closures, tuple_trait)]

extern "rust-call" fn foo<T: std::marker::Tuple>(_: T) {}

fn main() {
    foo(());
    foo((1, 2));
}
```
