### ISSUE TITLE
ICE on size_of_val and align_of_val with truly unsized types

### ISSUE THREAD

**Issue by matthiaskrgr** [bjorn3/rustc_codegen_cranelift#1244]
src/test/ui/extern/extern-types-size_of_val.rs

````rust
// run-pass
#![feature(extern_types)]

use std::mem::{align_of_val, size_of_val};

extern "C" {
    type A;
}

fn main() {
    let x: &A = unsafe { &*(1usize as *const A) };

    assert_eq!(size_of_val(x), 0);
    assert_eq!(align_of_val(x), 1);
}
````

````
error: internal compiler error: src/value_and_place.rs:160:38: Please use load_scalar for ByVal

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/compiler/rustc_errors/src/lib.rs:1391:9
stack backtrace:
   0:     0x7ff100ea1b20 - std::backtrace_rs::backtrace::libunwind::trace::h419808c895a1be3b
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7ff100ea1b20 - std::backtrace_rs::backtrace::trace_unsynchronized::h4cd640051eb1546f
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7ff100ea1b20 - std::sys_common::backtrace::_print_fmt::h6a643b487717d871
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7ff100ea1b20 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h84bab1c2a632e967
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7ff100efa85c - core::fmt::write::h41252a77742ac576
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/fmt/mod.rs:1198:17
   5:     0x7ff100e933c5 - std::io::Write::write_fmt::h68f35cff36a534dd
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/io/mod.rs:1672:15
   6:     0x7ff100ea4711 - std::sys_common::backtrace::_print::h82f0b1ac2501b6af
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7ff100ea4711 - std::sys_common::backtrace::print::h3dc7f0e84685b9ba
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7ff100ea4711 - std::panicking::default_hook::{{closure}}::h6ace3fe16ec6f7aa
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:295:22
   9:     0x7ff100ea43e3 - std::panicking::default_hook::h77c1c7afb621e87c
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:314:9
  10:     0x7ff10173f824 - rustc_driver[e83335c4a38137f8]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7ff100ea4ee6 - std::panicking::rust_panic_with_hook::h4cc32db16e14054a
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:702:17
  12:     0x7ff102719751 - std[a38b499b13c80ab0]::panicking::begin_panic::<rustc_errors[cf96977925b9f0c]::ExplicitBug>::{closure#0}
  13:     0x7ff102715e46 - std[a38b499b13c80ab0]::sys_common::backtrace::__rust_end_short_backtrace::<std[a38b499b13c80ab0]::panicking::begin_panic<rustc_errors[cf96977925b9f0c]::ExplicitBug>::{closure#0}, !>
  14:     0x7ff102744af6 - std[a38b499b13c80ab0]::panicking::begin_panic::<rustc_errors[cf96977925b9f0c]::ExplicitBug>
  15:     0x7ff102715dc6 - std[a38b499b13c80ab0]::panic::panic_any::<rustc_errors[cf96977925b9f0c]::ExplicitBug>
  16:     0x7ff102713195 - <rustc_errors[cf96977925b9f0c]::HandlerInner>::bug::<&alloc[aede580a0175a08c]::string::String>
  17:     0x7ff102712ef0 - <rustc_errors[cf96977925b9f0c]::Handler>::bug::<&alloc[aede580a0175a08c]::string::String>
  18:     0x7ff1027bd9dd - rustc_middle[a37307bbdd285edd]::ty::context::tls::with_context_opt::<rustc_middle[a37307bbdd285edd]::ty::context::tls::with_opt<rustc_middle[a37307bbdd285edd]::util::bug::opt_span_bug_fmt<rustc_span[550c183cd1c0caaa]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  19:     0x7ff1027c39d6 - rustc_middle[a37307bbdd285edd]::util::bug::opt_span_bug_fmt::<rustc_span[550c183cd1c0caaa]::span_encoding::Span>
  20:     0x7ff1027c3953 - rustc_middle[a37307bbdd285edd]::util::bug::bug_fmt
  21:     0x7ff0f9d70f92 - rustc_codegen_cranelift::value_and_place::CValue::load_scalar_pair::h72f87100b97fbae0
  22:     0x7ff0f9d7a997 - rustc_codegen_cranelift::intrinsics::codegen_regular_intrinsic_call::hf90da9e551c17d72
  23:     0x7ff0f9d77c81 - rustc_codegen_cranelift::intrinsics::codegen_intrinsic_call::hc59b3ef1cb233ea5
  24:     0x7ff0f9d5e38c - rustc_codegen_cranelift::abi::codegen_terminator_call::h3ee54347ad6a4b9f
  25:     0x7ff0f9cc514c - rustc_session::utils::<impl rustc_session::session::Session>::time::hb1b64207753ab68f
  26:     0x7ff0f9c70a43 - rustc_codegen_cranelift::base::codegen_fn_content::h7b8d3541509a524b
  27:     0x7ff0f9cc471b - rustc_session::utils::<impl rustc_session::session::Session>::time::h5486530910de022b
  28:     0x7ff0f9c6cbc1 - rustc_codegen_cranelift::base::codegen_fn::hc8e5fea087464384
  29:     0x7ff0f9cc316a - rustc_session::utils::<impl rustc_session::session::Session>::time::h2fc39d23b4fa3b7e
  30:     0x7ff0f9c64114 - rustc_codegen_cranelift::driver::aot::module_codegen::h2827a110f59deab8
  31:     0x7ff0f9ceb1be - rustc_query_system::dep_graph::graph::DepGraph<K>::with_task::h68aa13779d3bec18
  32:     0x7ff0f9cda8fa - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h355dce7525158f4e
  33:     0x7ff0f9d0d47e - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h381e907e74a9d74a
  34:     0x7ff0f9cc2fa2 - rustc_session::utils::<impl rustc_session::session::Session>::time::h13abb3ffbb1cca82
  35:     0x7ff0f9cfbf64 - rustc_codegen_cranelift::driver::time::h7de8a4d08c3be2ab
  36:     0x7ff0f9c66415 - rustc_codegen_cranelift::driver::aot::run_aot::h246f8b5585a00b3a
  37:     0x7ff0f9cb20d9 - <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate::h43a3212ba3170bbb
  38:     0x7ff1038d5727 - <rustc_session[16e8265f3bee680e]::session::Session>::time::<alloc[aede580a0175a08c]::boxed::Box<dyn core[303bee78761e0753]::any::Any>, rustc_interface[edbb2596f0660065]::passes::start_codegen::{closure#0}>
  39:     0x7ff1038c2d40 - <rustc_interface[edbb2596f0660065]::passes::QueryContext>::enter::<<rustc_interface[edbb2596f0660065]::queries::Queries>::ongoing_codegen::{closure#0}::{closure#0}, core[303bee78761e0753]::result::Result<alloc[aede580a0175a08c]::boxed::Box<dyn core[303bee78761e0753]::any::Any>, rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
  40:     0x7ff1038cca23 - <rustc_interface[edbb2596f0660065]::queries::Queries>::ongoing_codegen
  41:     0x7ff10388e8e1 - <rustc_interface[edbb2596f0660065]::interface::Compiler>::enter::<rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}::{closure#2}, core[303bee78761e0753]::result::Result<core[303bee78761e0753]::option::Option<rustc_interface[edbb2596f0660065]::queries::Linker>, rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
  42:     0x7ff10388aab0 - rustc_span[550c183cd1c0caaa]::with_source_map::<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_interface[edbb2596f0660065]::interface::create_compiler_and_run<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#1}>
  43:     0x7ff1038a50f2 - rustc_interface[edbb2596f0660065]::interface::create_compiler_and_run::<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>
  44:     0x7ff10388a2b2 - <scoped_tls[c1a1588d7c68db11]::ScopedKey<rustc_span[550c183cd1c0caaa]::SessionGlobals>>::set::<rustc_interface[edbb2596f0660065]::interface::run_compiler<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
  45:     0x7ff10388cfcf - std[a38b499b13c80ab0]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[edbb2596f0660065]::util::run_in_thread_pool_with_globals<rustc_interface[edbb2596f0660065]::interface::run_compiler<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>
  46:     0x7ff1038a5539 - <<std[a38b499b13c80ab0]::thread::Builder>::spawn_unchecked_<rustc_interface[edbb2596f0660065]::util::run_in_thread_pool_with_globals<rustc_interface[edbb2596f0660065]::interface::run_compiler<core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>, rustc_driver[e83335c4a38137f8]::run_compiler::{closure#1}>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>::{closure#0}, core[303bee78761e0753]::result::Result<(), rustc_errors[cf96977925b9f0c]::ErrorGuaranteed>>::{closure#1} as core[303bee78761e0753]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  47:     0x7ff100eae843 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6cafef397152c3f0
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/alloc/src/boxed.rs:1951:9
  48:     0x7ff100eae843 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0308246411b63a3b
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/alloc/src/boxed.rs:1951:9
  49:     0x7ff100eae843 - std::sys::unix::thread::Thread::new::thread_start::hd2e6d604897dcfa7
                               at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/sys/unix/thread.rs:108:17
  50:     0x7ff100c8054d - <unknown>
  51:     0x7ff100d05874 - clone
  52:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (f2d93935f 2022-07-02) running on x86_64-unknown-linux-gnu

note: compiler flags: -C panic=abort -Z panic-abort-tests -Z codegen-backend=/home/matthias/vcs/github/rustc_codegen_cranelift/build/lib/librustc_codegen_cranelift.so

query stack during panic:
end of query stack
fn std::mem::size_of_val(_1: &T) -> usize {
    debug val => _1;                     // in scope 0 at /home/matthias/vcs/github/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/mem/mod.rs:338:37: 338:40
    let mut _0: usize;                   // return place in scope 0 at /home/matthias/vcs/github/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/mem/mod.rs:338:49: 338:54
    let mut _2: *const T;                // in scope 0 at /home/matthias/vcs/github/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/mem/mod.rs:340:38: 340:41
    scope 1 {
    }

    bb0: {
        StorageLive(_2);                 // scope 1 at /home/matthias/vcs/github/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/mem/mod.rs:340:38: 340:41
        _2 = &raw const (*_1);           // scope 1 at /home/matthias/vcs/github/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/mem/mod.rs:340:38: 340:41
        _0 = std::intrinsics::size_of_val::<T>(move _2) -> bb1; // scope 1 at /home/matthias/vcs/github/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/mem/mod.rs:340:14: 340:42
                                         // mir::Constant
                                         // + span: /home/matthias/vcs/github/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/mem/mod.rs:340:14: 340:37
                                         // + literal: Const { ty: unsafe extern "rust-intrinsic" fn(*const T) -> usize {std::intrinsics::size_of_val::<T>}, val: Value(Scalar(<ZST>)) }
    }

    bb1: {
        StorageDead(_2);                 // scope 1 at /home/matthias/vcs/github/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/mem/mod.rs:340:41: 340:42
        return;                          // scope 0 at /home/matthias/vcs/github/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/mem/mod.rs:341:2: 341:2
    }
}

Instance { def: Item(WithOptConstParam { did: DefId(2:2136 ~ core[825a]::mem::size_of_val), const_param_did: None }), substs: [A] } _ZN4core3mem11size_of_val17h7a75a06480cd8b69E
error: aborting due to previous error
````

**Comment by bjorn3** [comment]
The result that size_of_val and align_of_val should return for truly unsized types is ill defined. I believe cg_llvm returns 0 and 1 respectively. I guess I could copy that.
