### ISSUE TITLE
src/test/ui/runtime/out-of-stack.rs test fails with SIGSEGV rather than giving SIGABRT as expected

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/rustc_codegen_cranelift#1301]
This has been happening for about a month now. I can't reproduce it locally and clearing the GHA cache fixes it until the next time it runs.

```
error: test run failed!
status: signal: 6 (SIGABRT) (core dumped)
command: "/home/runner/work/rustc_codegen_cranelift/rustc_codegen_cranelift/rust/build/x86_64-unknown-linux-gnu/test/ui/runtime/out-of-stack/a"
--- stdout -------------------------------
testing: silent-thread
------------------------------------------
--- stderr -------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(11)`,
 right: `Some(6)`', /home/runner/work/rustc_codegen_cranelift/rustc_codegen_cranelift/rust/src/test/ui/runtime/out-of-stack.rs:43:5
stack backtrace:
   0: rust_begin_unwind
             at /home/runner/work/rustc_codegen_cranelift/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /home/runner/work/rustc_codegen_cranelift/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/panicking.rs:65:14
   2: core::panicking::assert_failed_inner
             at /home/runner/work/rustc_codegen_cranelift/rustc_codegen_cranelift/build_sysroot/sysroot_src/library/core/src/panic.rs:57:9
   3: core::panicking::assert_failed
   4: out_of_stack::check_status
   5: out_of_stack::main
   6: core::ops::function::FnOnce::call_once
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bjorn3** [comment]
I haven't seen this again for quite a while.
