### ISSUE TITLE
Cannot compile simple_raytracer on master

### ISSUE THREAD

**Issue by vitiral** [bjorn3/rustc_codegen_cranelift#712]
[error.log](https://github.com/bjorn3/rustc_codegen_cranelift/files/3614369/error.log)

I'm on master and getting one of the tests to fail

```
./prepare.sh
cd simple-raytracer
cargo clean && ../cargo.sh build
```

It also fails when I run `./test.sh`

**Comment by vitiral** [comment]
The error:
```
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
...

```

Wait a sec... the cranelift IR is referencing "rayon core". Since threading isn't supported yet, wouldn't this error be expected?

```

fn  <rayon_core::job::JobRef as std::cmp::PartialEq>::eq(_1: &rayon_core::job::JobRef, _2: &rayon_core::job::JobRef) -> bool {
    let mut _0: bool;                    // return place in scope 0 at /home/rett/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:31:30: 31:39
    let _3: &*const ();                  // "__self_1_0" in scope 0 at /home/rett/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:33:5: 33:23
    let _4: &unsafe fn(*const ());       // "__self_1_1" in scope 0 at /home/rett/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:34:5: 34:37
```

**Comment by bjorn3** [comment]
Did you use commit https://github.com/bjorn3/rustc_codegen_cranelift/commit/c34ada7cca0607831dfae955214bc0b95f2ec312? I thought I fixed that error in https://github.com/bjorn3/rustc_codegen_cranelift/commit/77d33c1707277931e81ad0dea058e4bfc0b89b91.

> Since threading isn't supported yet, wouldn't this error be expected?

No, as it should just ignore statics being thread local and atomics being atomic. Threading should only give a runtime error.

**Comment by vitiral** [comment]
Sorry for the churn, must have done the pull wrong. It's fixed!
