### ISSUE TITLE
internal error on compiling rand 0.4.5

### ISSUE THREAD

**Issue by l4l** [bjorn3/rustc_codegen_cranelift#967]
Tried to build a project and rand has failed to build. Notice though, the build is only failing for 0.4.5 tag. Also tried 0.7.2 & master rand, both works fine. rustc_codegen_cranelift is a78f851 (current master).

Steps to reproduce:
```sh
$ git clone https://github.com/rust-random/rand.git
$ git checkout 0.4.5
$ $cg_clif_dir/cargo.sh build
```

<details>
  <summary>Here's the log</summary>

```
thread 'rustc' panicked at 'internal error: entered unreachable code', src/value_and_place.rs:126:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (3712e11a8 2020-04-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z panic-abort-tests -Z codegen-backend=/home/kitsu/dev/rustc_codegen_cranelift/target/release/librustc_codegen_cranelift.so -C debuginfo=2 -C incremental -C panic=abort -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

// WARNING: This output format is intended for human consumers only
// and is subject to change without notice. Knock yourself out.
fn os::next_u32(_1: &mut dyn for<'r> std::ops::FnMut(&'r mut [u8])) -> u32 {
    debug fill_buf => _1;                // in scope 0 at src/os.rs:61:13: 61:21
    let mut _0: u32;                     // return place in scope 0 at src/os.rs:61:49: 61:52
    let mut _2: [u8; 4] as UserTypeProjection { base: UserType(0), projs: [] }; // in scope 0 at src/os.rs:62:9: 62:16
    let _3: ();                          // in scope 0 at src/os.rs:63:5: 63:23
    let mut _4: &mut dyn for<'r> std::ops::FnMut(&'r mut [u8]); // in scope 0 at src/os.rs:63:5: 63:13
    let mut _5: (&mut [u8],);            // in scope 0 at src/os.rs:63:5: 63:23
    let mut _6: &mut [u8];               // in scope 0 at src/os.rs:63:14: 63:22
    let mut _7: &mut [u8; 4];            // in scope 0 at src/os.rs:63:14: 63:22
    let mut _8: &mut [u8; 4];            // in scope 0 at src/os.rs:63:14: 63:22
    let mut _9: [u8; 4];                 // in scope 0 at src/os.rs:64:45: 64:48
    scope 1 {
        debug buf => _2;                 // in scope 1 at src/os.rs:62:9: 62:16
        scope 2 {
        }
    }

    bb0: {
        StorageLive(_2);                 // bb0[0]: scope 0 at src/os.rs:62:9: 62:16
        _2 = [const 0u8; 4];             // bb0[1]: scope 0 at src/os.rs:62:28: 62:34
                                         // ty::Const
                                         // + ty: u8
                                         // + val: Value(Scalar(0x00))
                                         // mir::Constant
                                         // + span: src/os.rs:62:29: 62:30
                                         // + literal: Const { ty: u8, val: Value(Scalar(0x00)) }
        StorageLive(_3);                 // bb0[2]: scope 1 at src/os.rs:63:5: 63:23
        StorageLive(_4);                 // bb0[3]: scope 1 at src/os.rs:63:5: 63:13
        _4 = _1;                         // bb0[4]: scope 1 at src/os.rs:63:5: 63:13
        StorageLive(_5);                 // bb0[5]: scope 1 at src/os.rs:63:5: 63:23
        StorageLive(_6);                 // bb0[6]: scope 1 at src/os.rs:63:14: 63:22
        StorageLive(_7);                 // bb0[7]: scope 1 at src/os.rs:63:14: 63:22
        StorageLive(_8);                 // bb0[8]: scope 1 at src/os.rs:63:14: 63:22
        _8 = &mut _2;                    // bb0[9]: scope 1 at src/os.rs:63:14: 63:22
        _7 = _8;                         // bb0[10]: scope 1 at src/os.rs:63:14: 63:22
        _6 = move _7 as &mut [u8] (Pointer(Unsize)); // bb0[11]: scope 1 at src/os.rs:63:14: 63:22
        StorageDead(_7);                 // bb0[12]: scope 1 at src/os.rs:63:21: 63:22
        (_5.0: &mut [u8]) = move _6;     // bb0[13]: scope 1 at src/os.rs:63:5: 63:23
        _3 = const <dyn for<'r> std::ops::FnMut(&'r mut [u8]) as std::ops::FnMut<(&mut [u8],)>>::call_mut(move _4, move _5) -> bb1; // bb0[14]: scope 1 at src/os.rs:63:5: 63:23
                                         // ty::Const
                                         // + ty: for<'r> extern "rust-call" fn(&'r mut dyn for<'s> std::ops::FnMut(&'s mut [u8]), (&mut [u8],)) -> <dyn for<'s> std::ops::FnMut(&'s mut [u8]) as std::ops::FnOnce<(&mut [u8],)>>::Output {<dyn for<'r> std::ops::FnMut(&'r mut [u8]) as std::ops::FnMut<(&mut [u8],)>>::call_mut}
                                         // + val: Value(Scalar(<ZST>))
                                         // mir::Constant
                                         // + span: src/os.rs:63:5: 63:13
                                         // + literal: Const { ty: for<'r> extern "rust-call" fn(&'r mut dyn for<'s> std::ops::FnMut(&'s mut [u8]), (&mut [u8],)) -> <dyn for<'s> std::ops::FnMut(&'s mut [u8]) as std::ops::FnOnce<(&mut [u8],)>>::Output {<dyn for<'r> std::ops::FnMut(&'r mut [u8]) as std::ops::FnMut<(&mut [u8],)>>::call_mut}, val: Value(Scalar(<ZST>)) }
    }

    bb1: {
        StorageDead(_6);                 // bb1[0]: scope 1 at src/os.rs:63:22: 63:23
        StorageDead(_5);                 // bb1[1]: scope 1 at src/os.rs:63:22: 63:23
        StorageDead(_4);                 // bb1[2]: scope 1 at src/os.rs:63:22: 63:23
        StorageDead(_8);                 // bb1[3]: scope 1 at src/os.rs:63:23: 63:24
        StorageDead(_3);                 // bb1[4]: scope 1 at src/os.rs:63:23: 63:24
        StorageLive(_9);                 // bb1[5]: scope 2 at src/os.rs:64:45: 64:48
        _9 = _2;                         // bb1[6]: scope 2 at src/os.rs:64:45: 64:48
        _0 = const std::intrinsics::transmute::<[u8; 4], u32>(move _9) -> bb2; // bb1[7]: scope 2 at src/os.rs:64:14: 64:49
                                         // ty::Const
                                         // + ty: unsafe extern "rust-intrinsic" fn([u8; 4]) -> u32 {std::intrinsics::transmute::<[u8; 4], u32>}
                                         // + val: Value(Scalar(<ZST>))
                                         // mir::Constant
                                         // + span: src/os.rs:64:14: 64:44
                                         // + literal: Const { ty: unsafe extern "rust-intrinsic" fn([u8; 4]) -> u32 {std::intrinsics::transmute::<[u8; 4], u32>}, val: Value(Scalar(<ZST>)) }
    }

    bb2: {
        StorageDead(_9);                 // bb2[0]: scope 2 at src/os.rs:64:48: 64:49
        StorageDead(_2);                 // bb2[1]: scope 0 at src/os.rs:65:1: 65:2
        return;                          // bb2[2]: scope 0 at src/os.rs:65:2: 65:2
    }
}

Instance { def: Item(DefId(0:312 ~ rand[a149]::os[0]::next_u32[0])), substs: [] } _ZN4rand2os8next_u3217hc5e8cd6af0f7c50aE
warning: 11 warnings emitted

error: could not compile `rand`.
```

</details>

**UPD**: also tested for tags 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0-pre.0. All of these produce the same internal error. 0.3.9 produce compilation error (as well as default rustc) because it is probably too old. 0.5 & 0.5.0 & 0.5.1 compiling without any problem.

**Comment by bjorn3** [comment]
Thanks for reporting! I think I introduced a bug when I recently optimized the `mem::transmute` codegen.

**Comment by bjorn3** [comment]
I have a fix for this: dbb6678. I didn't push it to master yet, as it is based on a branch I currently don't want to switch away from in my local repo. (Aarch64 support based on a Cranelift PR that will be merged soon) Cherry-picking it onto master should work fine.

**Comment by l4l** [comment]
Tried to cherry-pick on top of master, but it still fails with the same message.

<details>
  <summary>Maybe backtrace will help?</summary>

```
thread 'rustc' panicked at 'internal error: entered unreachable code', src/value_and_place.rs:126:26
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: rustc_driver::report_ice
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  12: std::panicking::begin_panic
  13: rustc_codegen_cranelift::value_and_place::CValue::load_scalar
  14: rustc_codegen_cranelift::value_and_place::CPlace::write_cvalue_maybe_transmute
  15: rustc_codegen_cranelift::intrinsics::codegen_intrinsic_call
  16: rustc_codegen_cranelift::abi::codegen_terminator_call
  17: rustc_codegen_cranelift::base::codegen_fn_content
  18: rustc_session::utils::<impl rustc_session::session::Session>::time
  19: rustc_codegen_cranelift::base::trans_fn
  20: rustc_codegen_cranelift::driver::codegen_mono_items
  21: rustc_codegen_cranelift::driver::aot::module_codegen
  22: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  23: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  24: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  25: rustc_session::utils::<impl rustc_session::session::Session>::time
  26: rustc_codegen_cranelift::driver::time
  27: rustc_codegen_cranelift::driver::aot::run_aot
  28: rustc_codegen_cranelift::driver::codegen_crate
  29: <rustc_codegen_cranelift::CraneliftCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::codegen_crate
  30: rustc_interface::passes::start_codegen
  31: rustc_middle::ty::context::tls::enter_global
  32: rustc_interface::queries::Queries::ongoing_codegen
  33: rustc_interface::interface::run_compiler_in_existing_thread_pool
  34: scoped_tls::ScopedKey<T>::set
  35: rustc_ast::attr::with_globals
```

</details>

**Comment by bjorn3** [comment]
I just cherry-picked the commit on top of master and it worked fine for me. I have pushed it to master. If it still doesn't work for you, please tell me.

**Comment by l4l** [comment]
Quite weird caching issue, I tried with a newly cloned repo and that works, thanks!
